### PR TITLE
Yowsup2 port

### PR DESCRIPTION
**Pull request by dazzzl**
add sending images and locations
fix presence
some other small fixes

### CODE REVIEW

**Comment by moyamo** [comment]
This is really great. Thanks!

Are these features you have implemented?
- Google import
- Proper handling of receipts and acks
- Using File Transfer to send and receive media

I have a few small comments (line numbers are not exact):

**SpectrumBackend:364**:  I don't think those data size errors are errors. I think it just means that we have to wait for Spectrum to provide more data. It might clutter the logs.

**Bot:172**: On Debian, the fortune files are located in `/usr/share/games/fortunes`. I think you should have both versions.

Otherwise great work! I think stv0g's repository is still considered the main repository. Maybe you should send a pull request to his repository.

**Comment by dazzzl** [comment]
Hey moyamo,

I took the latest version from your for the merge.  I tried to port the features from my transwhat1 fork to the yowsup2 port. Still missing are notifications, like adding or status messages. 

The image and location features are implemented to work with conversations. With http-upload and http image download you do not need the file transfer feature from spectrum which is broken in the current release. It might work with spectrum and swiften3 ... I haven't tried this. Google import is also removed, because I do not need this. The received acknowledgement is working if you have a  client which support this (conversations, gaijm, pidgin with plugin) 

It is not really tested, so I decided to merge it first with your repository before we can merge it the main one. 

There some customization points, like the greetings from bot and the data path. Maybe we should move such thing in the configuration file.

**Comment by moyamo** [comment]
I tried uploading an image with conversations, it didn't work (version 1.7.0). Did I do something wrong? The greeting is in a configuration file (conf/motd) if I am not mistaken.

I was trying to add status messages (notifications) today, but I wasn't receiving them. Do you know of anything I should subscribe to first before I'm able to receive status messages?

**Comment by moyamo** [comment]
I see I get  a Decoder JPEG not available.

**Comment by dazzzl** [comment]
Do you use http file upload? You can check it under server info in conversations 

I am not sure, I think that there are no request for status messages. You will get a notification, if someone changes the status message

**Comment by dazzzl** [comment]
In transwhat? I am using PIL for image functions. Maybe you have to install PIL

**Comment by moyamo** [comment]
It turns out debians version of PIL doesn't seem to have JPEG support. Intalling it with pip did the trick, except now I get a permission denied error. Where does it try to save the file? I suggest it should use /tmp

**Comment by dazzzl** [comment]
I checked it on my server:
2015-11-10 18:38:06,933 INFO Session: Success: Image downloaded to /tmp/tmpEcMP4i

I am using the down and uploader from yowsup

**Comment by dazzzl** [comment]
yowsup downloader is using tempfile to create the file:
path = tempfile.mkstemp()[1]

**Comment by moyamo** [comment]
This is either a bug with yowsup or with pillow. `Pillow==3.0.0` doesn't work. `Pillow==2.9.0` is able to send images.

**Comment by dazzzl** [comment]
ok, I have:

PIL (1.1.7)
Pillow (2.8.1)

**Comment by dazzzl** [comment]
However, you need the transcoding only if you source image is not a jpeg ... 
Conversations in the latest version send now images in jpeg, but you have also to update your http file upload component of your server

**Comment by dazzzl** [comment]
Try to past the URL of an accessible jpeg  image to a WA user ... this should also send the image

**Comment by moyamo** [comment]
Currently yowsup just ignores UntrustedIdentityExceptions. This means if a whatsapp user changes their phone a yowsup user will not be able to send or receive messages to them. I suggest that yowsup atleast broadcasts and event when an UntrestedIdentityException occurs so that the application using yowsup can take appropriate action.

**Comment by moyamo** [comment]
I made a few commits. A few bugfixes. The last commit sends group messages via the bot if the user has not joined the group yet. This way the user will not lose group messages if he has not joined the group.

**Pull request merged**
